app = "real-estate-analytics-api"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8080"

[build]
  [build.args]
    PYTHON_VERSION = "3.10"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false  # Prevent spin-down
  auto_start_machines = true
  min_machines_running = 1   # Keep one instance running