services:
  - type: web
    name: realestate-ai-portfolio
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      echo "✅ Dependencies installed successfully"
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /api/health
